/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  tutorialSidebar: [
    {
      type: 'html',
      value: "<span class='sidebarHeading'>Overview</span>",
      defaultStyle: true,
    },
    'what-is-lineage',
    'how-it-work',
    'why-lineage',
    {
      type: 'html',
      value: '<hr class="horizontalBar" />',
      defaultStyle: true,
    },
    {
      type: 'html',
      value: "<span class='sidebarHeading'>Fundamental</span>",
      defaultStyle: true,
    },
    { type: 'autogenerated', dirName: 'fundamental' },
  ],
  sdkSidebar: [{ type: 'autogenerated', dirName: 'sdk' }],
  nodeSidebar: [
    {
      type: 'html',
      value: "<span class='sidebarHeading'>Implementation</span>",
      defaultStyle: true,
    },
    { type: 'autogenerated', dirName: 'node' },
  ],
  contractSidebar: [
    {
      type: 'html',
      value: "<span class='sidebarHeading'>Developing contracts</span>",
      defaultStyle: true,
    },
    { type: 'autogenerated', dirName: 'contract' },
  ],
};

module.exports = sidebars;
